import { StyleSheet } from 'react-native';

const CORES = {
  azul: '#007AFF',
  azulEscuro: '#0057D9',
  azulClaro: '#EAF3FF',
  azulNeon: '#5AC8FA',
  fundo: '#DCEBFF',
  fundoSecundario: '#BDD7FF',
  superficie: '#FFFFFF',
  superficieAlt: '#F8FBFF',
  texto: '#0F172A',
  textoSecundario: '#475569',
  textoSuave: '#64748B',
  borda: '#D4E4FF',
  sucesso: '#16A34A',
  sucessoFundo: '#EAF8EF',
  alerta: '#F97316',
  perigo: '#FF4D4F',
  sombra: '#93A4BF',
};

const styles = StyleSheet.create({
  containerInicio: {
    flex: 1,
    backgroundColor: CORES.fundo,
    paddingTop: 50,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: CORES.texto,
    letterSpacing: 0.4,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CORES.superficie,
    borderRadius: 18,
    paddingHorizontal: 18,
    marginBottom: 16,
    height: 54,
    borderWidth: 1,
    borderColor: CORES.borda,
    shadowColor: CORES.sombra,
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  conteudoLoja: {
    paddingHorizontal: 20,
    marginTop: 10,
    marginBottom: 14,
  },
  tituloSecao: {
    fontSize: 20,
    fontWeight: '800',
    color: CORES.azul,
    letterSpacing: 0.3,
  },
  scrollCategorias: {
    paddingLeft: 20,
    marginBottom: 20,
  },
  itemCategoria: {
    alignItems: 'center',
    marginRight: 15,
    width: 75,
  },
  boxImagemCategoria: {
    width: 60,
    height: 60,
    borderRadius: 18,
    backgroundColor: CORES.superficie,
    borderWidth: 1,
    borderColor: CORES.borda,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: CORES.sombra,
    shadowOpacity: 0.14,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  imagemCategoria: {
    width: '70%',
    height: '70%',
    resizeMode: 'contain',
  },
  textoCategoria: {
    marginTop: 6,
    fontSize: 11,
    fontWeight: '700',
    color: CORES.texto,
    textAlign: 'center',
  },
  card: {
    backgroundColor: CORES.superficie,
    padding: 16,
    borderRadius: 20,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: CORES.borda,
    shadowColor: CORES.sombra,
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardProdutoLoja: {
    backgroundColor: CORES.superficie,
    width: '48%',
    padding: 14,
    borderRadius: 24,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: CORES.borda,
    shadowColor: CORES.sombra,
    shadowOpacity: 0.14,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
    alignItems: 'stretch',
  },
  gradeProdutos: {
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  linhaGradeProdutos: {
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  listaProdutos: {
    paddingBottom: 30,
  },
  semProdutos: {
    width: '100%',
    alignItems: 'center',
    marginTop: 30,
  },
  destino: {
    fontSize: 18,
    fontWeight: '800',
    color: CORES.texto,
  },
  nomeProdutoGrid: {
    fontSize: 15,
    fontWeight: '800',
    color: CORES.texto,
    minHeight: 38,
  },
  precoProduto: {
    fontSize: 17,
    color: CORES.azul,
    fontWeight: '800',
    marginTop: 4,
  },
  textoEstoque: {
    fontSize: 12,
    color: CORES.textoSuave,
    marginTop: 4,
  },
  linhaAcoesProduto: {
    flexDirection: 'row',
    marginTop: 12,
    gap: 6,
  },
  botaoPequenoPrimario: {
    backgroundColor: CORES.azul,
    paddingVertical: 9,
    paddingHorizontal: 8,
    borderRadius: 14,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textoBotaoPequenoPrimario: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 11,
    textAlign: 'center',
    width: '100%',
  },
  botaoPequenoSecundario: {
    backgroundColor: CORES.azulClaro,
    paddingVertical: 9,
    paddingHorizontal: 8,
    borderRadius: 14,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: CORES.borda,
  },
  textoBotaoPequenoSecundario: {
    color: CORES.azul,
    fontWeight: '700',
    fontSize: 11,
    textAlign: 'center',
    width: '100%',
  },
  botaoPequenoNeutro: {
    backgroundColor: CORES.superficieAlt,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 14,
  },
  textoBotaoPequenoNeutro: {
    color: CORES.texto,
    fontWeight: '700',
    fontSize: 12,
  },
  badgeCarrinho: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: CORES.perigo,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  badgeCarrinhoTexto: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },

  container: {
    flexGrow: 1,
    backgroundColor: CORES.fundo,
    paddingHorizontal: 24,
    justifyContent: 'center',
    paddingBottom: 20,
    paddingTop: 20,
  },
  titulo: {
    fontSize: 28,
    fontWeight: '800',
    color: CORES.azul,
    textAlign: 'center',
    marginBottom: 10,
    letterSpacing: 0.4,
  },
  subtitulo: {
    fontSize: 16,
    color: CORES.textoSecundario,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 24,
  },
  input: {
    backgroundColor: CORES.superficie,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 20,
    marginBottom: 18,
    fontSize: 16,
    borderWidth: 1,
    borderColor: CORES.borda,
    color: CORES.texto,
    shadowColor: CORES.sombra,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  botao: {
    backgroundColor: CORES.azul,
    borderRadius: 18,
    paddingVertical: 17,
    alignItems: 'center',
    marginTop: 10,
    width: '100%',
    shadowColor: CORES.azulEscuro,
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  textoBotao: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '600',
  },
  buttonSecondary: {
    marginTop: 15,
    alignItems: 'center',
  },
  buttonText: {
    color: CORES.azul,
    fontSize: 16,
    fontWeight: '700',
  },
  cardPerfil: {
    backgroundColor: CORES.superficie,
    width: '100%',
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: CORES.borda,
    shadowColor: CORES.sombra,
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  blocoInfo: {
    marginBottom: 4,
  },
  labelInfo: {
    fontSize: 12,
    color: CORES.textoSuave,
    fontWeight: '800',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  infoTexto: {
    fontSize: 16,
    color: CORES.texto,
    fontWeight: '600',
  },
  divisor: {
    height: 1,
    backgroundColor: '#E2E8F0',
    marginVertical: 10,
    width: '100%',
  },
  perfilHero: {
    width: '100%',
    backgroundColor: CORES.azul,
    borderRadius: 28,
    paddingVertical: 30,
    paddingHorizontal: 24,
    alignItems: 'center',
    marginBottom: 18,
    shadowColor: CORES.azulEscuro,
    shadowOpacity: 0.32,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 8,
  },
  perfilAvatar: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: 'rgba(255,255,255,0.18)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  perfilNomeDestaque: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  perfilEmailDestaque: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.88)',
    marginTop: 6,
    textAlign: 'center',
  },
  perfilBadgeId: {
    marginTop: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  perfilBadgeIdTexto: {
    color: CORES.azul,
    fontWeight: '800',
    fontSize: 13,
  },
  perfilStatsRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
    gap: 10,
  },
  perfilStatCard: {
    flex: 1,
    backgroundColor: CORES.superficie,
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: CORES.borda,
    shadowColor: CORES.sombra,
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  perfilStatValor: {
    fontSize: 18,
    fontWeight: '800',
    color: CORES.texto,
  },
  perfilStatLabel: {
    fontSize: 12,
    color: CORES.textoSuave,
    marginTop: 6,
    textTransform: 'uppercase',
  },
  perfilSecaoTitulo: {
    fontSize: 18,
    fontWeight: '800',
    color: CORES.texto,
    marginBottom: 16,
  },
  perfilBotaoAdmin: {
    backgroundColor: CORES.azul,
    marginBottom: 15,
  },

  areaUpload: {
    width: '100%',
    height: 400, 
    backgroundColor: CORES.superficie,
    borderRadius: 20,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: CORES.azul,
    borderStyle: 'dashed',
    overflow: 'hidden',
  },
  imagemPreview: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain', 
  },
  imagemProdutoBox: {
    width: 110,
    height: 90,
    marginRight: 15,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: CORES.superficieAlt,
    borderRadius: 16,
    overflow: 'hidden',
  },
  imagemProdutoCard: {
    width: '100%',
    height: '100%',
  },
  imagemProdutoGridBox: {
    width: '100%',
    height: 120,
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: CORES.superficieAlt,
    borderRadius: 18,
    overflow: 'hidden',
  },
  imagemProdutoGrid: {
    width: '92%',
    height: '92%',
  },
  infoProdutoGrid: {
    flex: 1,
  },
  textoUpload: {
    color: CORES.azul,
    fontSize: 16,
    fontWeight: '800',
  },
  containerCarrinho: {
    flexGrow: 1,
    backgroundColor: CORES.fundo,
    paddingHorizontal: 20,
    paddingTop: 30,
    paddingBottom: 40,
  },
  cardCarrinhoVazio: {
    backgroundColor: CORES.superficie,
    borderRadius: 22,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: CORES.borda,
  },
  cardCarrinho: {
    backgroundColor: CORES.superficie,
    borderRadius: 22,
    padding: 15,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: CORES.borda,
    shadowColor: CORES.sombra,
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  infoCarrinho: {
    flex: 1,
  },
  imagemProdutoCarrinhoBox: {
    width: 95,
    height: 95,
    marginRight: 15,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: CORES.superficieAlt,
    borderRadius: 16,
    overflow: 'hidden',
  },
  imagemProdutoCarrinho: {
    width: 88,
    height: 88,
  },
  linhaQuantidade: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 8,
  },
  botaoQuantidade: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: CORES.azulClaro,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textoBotaoQuantidade: {
    color: CORES.azul,
    fontSize: 18,
    fontWeight: '800',
  },
  quantidadeTexto: {
    marginHorizontal: 14,
    fontSize: 16,
    fontWeight: '800',
    color: CORES.texto,
  },
  linkRemover: {
    color: CORES.perigo,
    fontWeight: '800',
  },
  resumoCarrinho: {
    backgroundColor: CORES.superficie,
    borderRadius: 22,
    padding: 20,
    marginTop: 10,
    borderWidth: 1,
    borderColor: CORES.borda,
  },
  totalCarrinho: {
    fontSize: 22,
    fontWeight: '800',
    color: CORES.texto,
    marginBottom: 12,
  },
  botaoDesabilitado: {
    opacity: 0.75,
  },
  linhaCarregando: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  pixModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(2, 6, 23, 0.74)',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  pixModalCard: {
    backgroundColor: '#F8FBFF',
    borderRadius: 30,
    paddingVertical: 24,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: '#BBD5FF',
    shadowColor: '#020617',
    shadowOpacity: 0.28,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  pixModalTag: {
    alignSelf: 'flex-start',
    backgroundColor: '#007AFF',
    color: '#FFFFFF',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 14,
  },
  pixModalTitulo: {
    fontSize: 25,
    fontWeight: '900',
    color: '#020617',
    marginBottom: 10,
  },
  pixModalTexto: {
    fontSize: 15,
    color: '#334155',
    lineHeight: 22,
    marginBottom: 18,
  },
  pixQrContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 18,
    borderWidth: 1,
    borderColor: '#D4E4FF',
  },
  pixCodigoInput: {
    minHeight: 108,
    backgroundColor: '#EAF3FF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#C6DBFF',
    color: '#0F172A',
    fontSize: 13,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  pixFeedbackTexto: {
    textAlign: 'center',
    color: '#334155',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 12,
  },
  pixBotaoFechar: {
    marginTop: 16,
    backgroundColor: '#FF3B30',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
  },
  pixBotaoFecharTexto: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  containerDetalhes: {
    flexGrow: 1,
    backgroundColor: CORES.fundo,
    padding: 20,
  },
  cardDetalhesImagem: {
    backgroundColor: CORES.superficie,
    borderRadius: 24,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
    minHeight: 280,
    borderWidth: 1,
    borderColor: CORES.borda,
  },
  imagemDetalhes: {
    width: '100%',
    height: 240,
  },
  cardDetalhes: {
    backgroundColor: CORES.superficie,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: CORES.borda,
  },
  tituloDetalhes: {
    fontSize: 26,
    fontWeight: '800',
    color: CORES.texto,
    marginBottom: 8,
  },
  precoDetalhes: {
    fontSize: 24,
    color: CORES.azul,
    fontWeight: '800',
    marginBottom: 12,
  },
  textoDetalhes: {
    fontSize: 15,
    color: CORES.textoSecundario,
    marginBottom: 6,
  },
  descricaoDetalhes: {
    fontSize: 15,
    color: CORES.textoSuave,
    lineHeight: 22,
    marginTop: 10,
    marginBottom: 20,
  },
  botaoSecundarioProduto: {
    borderWidth: 1,
    borderColor: CORES.azul,
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 12,
    backgroundColor: CORES.azulClaro,
  },
  textoBotaoSecundario: {
    color: CORES.azul,
    fontSize: 16,
    fontWeight: '800',
  },
  containerRadar: {
    flexGrow: 1,
    backgroundColor: CORES.fundoSecundario,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 36,
  },
  radarHero: {
    backgroundColor: 'rgba(255,255,255,0.45)',
    borderRadius: 30,
    paddingVertical: 24,
    paddingHorizontal: 24,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.65)',
    shadowColor: CORES.sombra,
    shadowOpacity: 0.16,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  radarHeroLabel: {
    alignSelf: 'flex-start',
    backgroundColor: CORES.azul,
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    marginBottom: 14,
  },
  radarTitulo: {
    fontSize: 32,
    fontWeight: '800',
    color: CORES.texto,
    marginBottom: 10,
    letterSpacing: 0.3,
  },
  radarHeroTexto: {
    fontSize: 15,
    color: CORES.textoSecundario,
    lineHeight: 24,
  },
  radarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  radarQuadrado: {
    width: '48%',
    minHeight: 220,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 26,
    padding: 18,
    marginBottom: 16,
    shadowColor: CORES.sombra,
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
  },
  radarQuadradoTitulo: {
    fontSize: 18,
    fontWeight: '800',
    color: CORES.texto,
    marginBottom: 8,
  },
  radarCardTag: {
    alignSelf: 'flex-start',
    backgroundColor: CORES.azulClaro,
    color: CORES.azul,
    fontSize: 11,
    fontWeight: '800',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    marginBottom: 14,
  },
  radarDestaque: {
    fontSize: 34,
    fontWeight: '900',
    color: CORES.azul,
    marginBottom: 8,
  },
  radarTextoPrincipal: {
    fontSize: 16,
    fontWeight: '700',
    color: CORES.texto,
    marginBottom: 6,
  },
  radarTextoSecundario: {
    fontSize: 13,
    color: CORES.textoSuave,
    lineHeight: 20,
  },
  radarBotao: {
    marginTop: 14,
    backgroundColor: CORES.azul,
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: 'center',
    shadowColor: CORES.azulEscuro,
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  radarBotaoTexto: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 13,
  },
  radarClimaCentro: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 120,
    gap: 10,
  },
  radarClimaTopo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 12,
  },
  radarClimaIconeBox: {
    width: 68,
    height: 68,
    borderRadius: 20,
    backgroundColor: '#EAF3FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radarClimaEmoji: {
    fontSize: 36,
  },
  comunidadeInput: {
    minHeight: 110,
    marginBottom: 10,
  },
  comunidadeContainer: {
    flexGrow: 1,
    backgroundColor: CORES.fundo,
    paddingHorizontal: 24,
    paddingTop: 80,
    paddingBottom: 34,
  },
  comunidadeCardPublicar: {
    paddingTop: 22,
  },
  comunidadeCardPosts: {
    minHeight: 220,
  },
  comunidadeTextoApoio: {
    fontSize: 14,
    lineHeight: 21,
    color: '#64748B',
    marginTop: -6,
    marginBottom: 16,
  },
  comunidadeEstadoVazio: {
    flex: 1,
    minHeight: 140,
    borderRadius: 18,
    backgroundColor: '#F8FBFF',
    borderWidth: 1,
    borderColor: '#D7E7FF',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  comunidadeEstadoVazioTitulo: {
    fontSize: 18,
    fontWeight: '800',
    color: '#123A63',
    marginBottom: 8,
    textAlign: 'center',
  },
  comunidadeEstadoVazioTexto: {
    fontSize: 14,
    lineHeight: 21,
    color: '#6E86A0',
    textAlign: 'center',
  },
  comunidadeResumoLinha: {
    width: '100%',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
  },
  comunidadeResumoCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D7E7FF',
    shadowColor: '#0C2340',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  comunidadeResumoNumero: {
    fontSize: 22,
    fontWeight: '800',
    color: '#007AFF',
    textAlign: 'center',
  },
  comunidadeResumoRotulo: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '700',
    color: '#64748B',
    textAlign: 'center',
  },
  comunidadeLinha: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  comunidadePosicao: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: CORES.azulClaro,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  comunidadePosicaoTexto: {
    color: CORES.azul,
    fontWeight: '800',
    fontSize: 15,
  },
  comunidadeLinhaConteudo: {
    flex: 1,
  },
  comunidadeNome: {
    fontSize: 16,
    fontWeight: '800',
    color: CORES.texto,
    marginBottom: 4,
  },
  comunidadeMeta: {
    fontSize: 13,
    color: CORES.textoSuave,
    marginTop: 8,
  },
  comunidadeBloco: {
    backgroundColor: 'rgba(255,255,255,0.68)',
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
  },
  comunidadeTitulo: {
    fontSize: 16,
    fontWeight: '800',
    color: CORES.texto,
    marginBottom: 8,
  },
  checklistContainer: {
    flexGrow: 1,
    backgroundColor: CORES.fundoSecundario,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 36,
  },
  checklistPainelTopo: {
    backgroundColor: 'rgba(255,255,255,0.42)',
    borderRadius: 28,
    padding: 22,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.68)',
    marginBottom: 18,
    shadowColor: CORES.sombra,
    shadowOpacity: 0.17,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  checklistLabelTopo: {
    alignSelf: 'flex-start',
    backgroundColor: CORES.azul,
    color: '#FFFFFF',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 14,
    letterSpacing: 1,
  },
  checklistTitulo: {
    fontSize: 28,
    fontWeight: '900',
    color: CORES.texto,
    marginBottom: 8,
  },
  checklistSubtitulo: {
    color: CORES.textoSecundario,
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 18,
  },
  checklistBlocoProgresso: {
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
  },
  checklistProgressoValor: {
    fontSize: 38,
    fontWeight: '900',
    color: CORES.azul,
    marginBottom: 4,
  },
  checklistProgressoTexto: {
    color: CORES.textoSuave,
    fontSize: 14,
    marginBottom: 14,
  },
  checklistBarraTrilho: {
    height: 12,
    backgroundColor: '#B7D1F8',
    borderRadius: 999,
    overflow: 'hidden',
  },
  checklistBarraPreenchida: {
    height: '100%',
    backgroundColor: CORES.azul,
    borderRadius: 999,
  },
  checklistLista: {
    marginBottom: 22,
  },
  checklistItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 22,
    padding: 17,
    marginBottom: 12,
    borderWidth: 1,
    shadowColor: CORES.sombra,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  checklistItemCardPendente: {
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderColor: 'rgba(255,255,255,0.74)',
  },
  checklistItemCardAtivo: {
    backgroundColor: CORES.sucessoFundo,
    borderColor: CORES.sucesso,
  },
  checklistItemTextoBox: {
    flex: 1,
    paddingRight: 14,
  },
  checklistItemTitulo: {
    color: CORES.texto,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  checklistItemTituloAtivo: {
    color: '#1F7A3D',
    textDecorationLine: 'line-through',
    opacity: 0.75,
  },
  checklistItemStatus: {
    color: CORES.textoSuave,
    fontSize: 13,
    fontWeight: '700',
  },
  checklistItemStatusAtivo: {
    color: '#1F7A3D',
    opacity: 0.8,
  },
  checklistBotaoMissao: {
    borderRadius: 20,
    paddingVertical: 18,
    alignItems: 'center',
  },
  checklistBotaoBloqueado: {
    backgroundColor: '#334155',
  },
  checklistBotaoAtivo: {
    backgroundColor: CORES.sucesso,
  },
  checklistBotaoTexto: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  rotaContainer: {
    flex: 1,
    backgroundColor: CORES.azulClaro,
  },
  rotaLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: '#F3F8FF',
  },
  rotaLoadingText: {
    marginTop: 16,
    fontSize: 16,
    fontWeight: '600',
    color: '#1E3A5F',
  },
  rotaErrorTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#123A63',
    marginBottom: 10,
  },
  rotaErrorText: {
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    color: '#4B6584',
  },
  rotaMap: {
    flex: 1,
  },
  rotaHeaderOverlay: {
    position: 'absolute',
    top: 16,
    left: 16,
    right: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.75)',
    shadowColor: '#0C2340',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  rotaHeaderEyebrow: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#0A6CFF',
    marginBottom: 6,
  },
  rotaHeaderTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#123A63',
  },
  rotaTelemetryPanel: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 22,
    padding: 18,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    shadowColor: '#0C2340',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 10,
  },
  rotaTelemetryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
    gap: 10,
  },
  rotaMetricCard: {
    flex: 1,
    backgroundColor: '#F4F8FF',
    borderRadius: 20,
    minHeight: 118,
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rotaMetricLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    color: '#5B7796',
    marginBottom: 10,
    textAlign: 'center',
  },
  rotaMetricValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#123A63',
    textAlign: 'center',
  },
  rotaMetricValueTempo: {
    fontSize: 18,
    letterSpacing: 0.4,
  },
  rotaMetricUnit: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: '600',
    color: '#6E86A0',
    textAlign: 'center',
  },
  rotaActionButton: {
    minHeight: 58,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rotaActionButtonStart: {
    backgroundColor: '#007AFF',
  },
  rotaActionButtonStop: {
    backgroundColor: '#E53935',
  },
  rotaActionButtonText: {
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.8,
    color: '#FFFFFF',
  },
});

export default styles;
